### ISSUE TITLE
Don't heat the bed

### ISSUE THREAD

**Issue by carlosrondini** [makerbase-mks/MKS-Robin-E3P#1]
I have an ender 3 with MKS-Robin-E3P and TMC2209.
I followed the settings:
Set default_envs = mks_robin_e3p
Set #define SERIAL_PORT -1
set #define SERIAL_PORT_2 3
Set #define MOTHERBOARD BOARD_MKS_ROBIN_E3P
#define INVERT_X_DIR false
#define EEPROM_SETTINGS
#define X_DRIVER_TYPE TMC2209

When used MKS UI does not print, does not heat the bed.
But, using 128x64 Marlin UI or Color Marlin UI works.

I used:
Mks-Robin-Nano-Marlin2.0-Firmware
marlin2.0.7

**Comment by mks-viva** [comment]
Can be check temp on MKS TS35 screen when you use MKS UI? Can you provide some picture when you use MKS UI printing.

**Comment by carlosrondini** [comment]
> Can be check temp on MKS TS35 screen when you use MKS UI? Can you provide some picture when you use MKS UI printing.

Yes. It stays at room temperature, does not increase.
![20201025_233356](https://user-images.githubusercontent.com/2701086/97129127-d5e4d900-171c-11eb-99c5-5d7b92405d4e.jpg)

**Comment by mks-viva** [comment]
Please provide your use the gcode file to me.

**Comment by carlosrondini** [comment]
[CE3_CableClip1.zip](https://github.com/makerbase-mks/MKS-Robin-E3P/files/5442430/CE3_CableClip1.zip)

**Comment by mks-viva** [comment]
Ok! We will test it.

**Comment by mks-viva** [comment]
MKS Test it is OK. Can you format your TF card?

**Comment by carlosrondini** [comment]
Hello, unbelievably, it worked.
Thank you.

**Comment by mks-viva** [comment]
OK! We will close it.
