### ISSUE TITLE
Not enought precision in Z offsets value in MKS UI.

### ISSUE THREAD

**Issue by myckiecat** [makerbase-mks/MKS-Robin-E3P#10]
I think there is a problem with accuracy in Z offsets when setting up a MKS Touch.
You put online one decimal digit precision in this value in the UI and this is not enought to calibrate offset with precision...
Please update, because almost two digits are necesary to setting up a true zoffset in your MKS UI.

If not, i'm not able to setup your MKS Touch with this board properly.
I tried modifying this value in marlin , but i dont know if it's applied correctly the offsets, because when i go to MKS UI Z offsets menu, i see a rounded value....

Thanks.

**Comment by MKS-Sean** [comment]
I got this bug and I will fix it, because we usually use babystep to adjust the value of zoffset, which is rarely used in parameter settings. You found this problem

**Comment by MKS-Sean** [comment]
@ Fixed this problem

**Comment by myckiecat** [comment]
> I got this bug and I will fix it, because we usually use babystep to adjust the value of zoffset, which is rarely used in parameter settings. You found this problem

Thanks!!

**Comment by myckiecat** [comment]
> @ Fixed this problem

Tested it and now it's really nice :)
Thank you for fixing it.
