### ISSUE TITLE
No compila MKS-Robin-E3P-master/Source-code

### ISSUE THREAD

**Issue by BenjaGaldames** [makerbase-mks/MKS-Robin-E3P#21]
Hola,

Tras descargar el archivo y generarlo con VSCode / PlatformIO / Marlin Firmware,  me da este error. 

Ayuda  por favor!!!

![1](https://user-images.githubusercontent.com/89672980/131203205-3072a569-305d-4a82-87a9-8d6e0e31457f.png)

**Comment by mks-viva** [comment]
May be same sa #21
