### ISSUE TITLE
No compila MKS-Robin-E3P-master / Source-code

### ISSUE THREAD

**Issue by BenjaGaldames** [makerbase-mks/MKS-Robin-E3P#22]
Hola,

Tras descargar el archivo y generarlo con VSCode / PlatformIO / Marlin Firmware, me da este error.

Ayuda por favor !!!

<img width="631" alt="1" src="https://user-images.githubusercontent.com/89672980/131205247-3df930b5-0412-4be1-b349-aa7e6e3770ca.png">

**Comment by mks-viva** [comment]
Please provide your source code to me and i need test it.

**Comment by BenjaGaldames** [comment]
Hola,

Código fuente en el enlace.

https://drive.google.com/file/d/19gOYfWlFfZKFq_7VERm1705jKhZPbpVN/view?usp=sharing

<img width="586" alt="1" src="https://user-images.githubusercontent.com/89672980/131585625-6ba62948-5bd5-4274-a75e-8e6d0db2ca96.png">

**Comment by mks-viva** [comment]
I has compile it and it's ok. Maybe you need to try a few more times.
![image](https://user-images.githubusercontent.com/16629551/131607316-c4793e6d-5ad5-41ab-84da-b0e3468021be.png)
[Robin_e3p.zip](https://github.com/makerbase-mks/MKS-Robin-E3P/files/7088042/Robin_e3p.zip)

**Comment by BenjaGaldames** [comment]
Hola,

Al compilar en otra computadora, me funciono, al parecer no funciona en todas las computadoras.
El problema que tengo ahora es que los finales de carrera no me los toma en cuenta, tengo una CR-10 en modo Dir.

Ayúdame con los finales de carrera.

https://drive.google.com/file/d/1EKTz9yING4X7zVFF-XFmzvSjxvPUVdJJ/view?usp=sharing

**Comment by mks-viva** [comment]
[Robin_e3p.zip](https://github.com/makerbase-mks/MKS-Robin-E3P/files/7096618/Robin_e3p.zip)

**Comment by BenjaGaldames** [comment]
Aun no me funcionan los finales de carrera.

Necesito una solución para que funcionen los finales de carrera.
