### ISSUE TITLE
MKS-Robin-E3P with TS35 UI issue

### ISSUE THREAD

**Issue by DanJunior78** [makerbase-mks/MKS-Robin-E3P#3]
I´ve tried the 2 LCD like screen ui versions. Both are not working properly with the screen.
On both the screen is flipped (see picture) and the touch function too.

Could this be somehow corrected?

![photo_2020-11-06_22-14-49](https://user-images.githubusercontent.com/55321080/98415379-81771d00-207d-11eb-9e1d-41002c0c6343.jpg)

**Comment by DanJunior78** [comment]
Ok, is a bug in Marlin which will be solved for Marlin 2.0.8.x ... or you can use latest Marlin Bugfix version...

**Comment by mks-viva** [comment]
@DanJunior78 
Hi! Thanks for the feedback, this may help other users.
