### ISSUE TITLE
MKS PWC

### ISSUE THREAD

**Issue by Surax98** [makerbase-mks/MKS-Robin-E3P#4]
I can't properly set up my PWC module.I am following the guide you posted, but I'm unable to make it works. I tried to remap my pins too, but nothing seems to work. Is it a bug or am I just missing something? Just to mention, I'am obviously using a Robin E3P.

**Comment by mks-viva** [comment]
Can you provide your motherboard wirings to me?

**Comment by Surax98** [comment]
![Senzanome](https://user-images.githubusercontent.com/33400876/99796747-4faa8f80-2b2e-11eb-9e4e-4f479e939c60.png)
This is how i connected signal pins. I can assure the rest is correctly connected (220V plug to input and 220V output to power supply paying attention to not swap L and N. Logic power to 5V/GND on the same connector as the signal pins). When I unplug the printer and then replug, the outage detection seems to work and in fact, it resumes from where stopped, but I can't make it work with the M81 code. Just says "*3d printer name* OFF" and keep being ON. I attach how i defined pins too.

![Cattura](https://user-images.githubusercontent.com/33400876/99797127-f98a1c00-2b2e-11eb-91be-c98961510222.PNG)

**Comment by mks-viva** [comment]
MKS PWC's PW_DET connect to MKS Robin E3P's MT-DET
MKS PWC's PW_OFF connect to MKS Robin E3P's PB0; PW_OFF must use have not pullup IO, PA4 has pullup
So, you pin define like this:
#define KILL_PIN    PA4
#define PS_ON_PIN   PB0
![image](https://user-images.githubusercontent.com/16629551/99871930-07b46700-2c19-11eb-8732-7258190b62bc.png)

**Comment by Surax98** [comment]
I tried to follow defines from your screenshot, but it didn't work. I'll try to follow the ones you posted and let you know

**Comment by mks-viva** [comment]
Can you provide your MKS Robin E3P's config to me and i config it and it work ok, i will send it for you.

**Comment by Surax98** [comment]
[Marlin E3P.zip](https://github.com/makerbase-mks/MKS-Robin-E3P/files/5577327/Marlin.E3P.zip)
I attached everything, so you can check every file (configuration, adv_config, pins, ecc ecc). Just let me know the quickest possibile, including how to physically connect pins correctly

**Comment by Surax98** [comment]
Meanwhile, I tried to define pins in this way:
#define KILL_PIN PA4
#define PS_ON_PIN PB0

on PA4 I have PW_DET, on PB0 I have PW_OFF. still can't shut down printer using M81

**Comment by Surax98** [comment]
@mks-viva Any news? Please, I need to make it work...

**Comment by mks-viva** [comment]
Hi! I has test it and it is OK
1. because you has use Marlin color UI and you has enable #define TFT_480x320_SPI, so you need settings pin in pins_MKS_ROBIN_E3P.h file;
![image](https://user-images.githubusercontent.com/16629551/99956923-cd39fe00-2dc1-11eb-81da-882f886de4c0.png)

**Comment by Surax98** [comment]
@mks-viva can you please provide me the right pin file so i have no chance to do something wrong?

**Comment by mks-viva** [comment]
I upload pins file to here, you can download it.

[pins_MKS_ROBIN_E3P.zip](https://github.com/makerbase-mks/MKS-Robin-E3P/files/5582660/pins_MKS_ROBIN_E3P.zip)

**Comment by Surax98** [comment]
@mks-viva I used the pin file provided but sending M81 still keeps my board ON.... LCD keeps being on, extruder fan keeps being on, everything keeps being on... Just extruder and heated bed stops being hot (but i think this is just because temps are set to 0 through software command).....

**Comment by Surax98** [comment]
@mks-viva I fixed it! I digged into M80-M81 gcode file (M80_M81.cpp) and found out this thing:
![Cattura](https://user-images.githubusercontent.com/33400876/99965069-9ac5dc00-2d94-11eb-8f5d-5c054d8ef099.PNG)
In my pins file, I had SUICIDE_PIN set to PB2, which, apparently, doesn't exist on the E3P (or i can't find it on the pinout diagram)
![Cattura2](https://user-images.githubusercontent.com/33400876/99965592-56870b80-2d95-11eb-9ce3-598a3dc9e6de.PNG)
So, i just commented out this pin, forcing M81 to use the function PSU_OFF() instead of suicide() and that worked!

**Comment by mks-viva** [comment]
@Surax98 
So, this problem are solved?

**Comment by Surax98** [comment]
Yes, solved

**Comment by Surax98** [comment]
Yes, solved
