### ISSUE TITLE
Get some errors and can't print with Microsd

### ISSUE THREAD

**Issue by Rotciv333** [makerbase-mks/MKS-Robin-E3P#5]
[MKS-Robin-E3P.zip](https://github.com/makerbase-mks/MKS-Robin-E3P/files/5721137/MKS-Robin-E3P.zip)
![Ufd52735e6e1f4b4c9decacbf7f6e8937Z](https://user-images.githubusercontent.com/76400687/102717792-ecef1400-42e4-11eb-80eb-976088b29e32.png)

Hello

I bought a MKS Robin E3P for my creality CR10 S5, i changed the parameters to adjusts the new dimensions in marlin, compiled and uploaded... The problem is, when i try to print with microSD, the extrusors put on position to start and entry in pause, if a push on resume don't start and goes to pause mode...

I tried to print with my pc to show what's happen, using repeteir-host, and printer aparently make the impresion, but, i don't calibrate the printer and don't extrude as well...

Please need help, i don't what is happen, attach the marlin, and some captures from some errors...

Thank you

**Comment by AleefRibeiro** [comment]
I have the same error for Ender 3, I'm using Cura to Slice the STL but it locks up and doesn't print anything, if I turn on the printer via USB I can print.

Did you manage to solve the problem?
