### ISSUE TITLE
Bltouch issue

### ISSUE THREAD

**Issue by edouardkleinhans** [makerbase-mks/MKS-Robin-E3P#6]
Hello, 

I can't add a bltouch to this motherboard.

bltouch is connected to PA8 and endstop to Z endstop. 

Can you help me on this ?

[Configuration_adv.h.txt](https://github.com/makerbase-mks/MKS-Robin-E3P/files/5747428/Configuration_adv.h.txt)
[Configuration.h.txt](https://github.com/makerbase-mks/MKS-Robin-E3P/files/5747429/Configuration.h.txt)

**Comment by mks-viva** [comment]
Hi! You can refer to here: https://github.com/makerbase-mks/MKS-Robin-E3P/tree/master/Firmware
![image](https://user-images.githubusercontent.com/16629551/103254041-bdb06500-49be-11eb-8fce-c6b3c576a280.png)

**Comment by edouardkleinhans** [comment]
That's what I try, and it doesn't work.

**Comment by mks-viva** [comment]
Can you provide your wiring picture to me?

**Comment by edouardkleinhans** [comment]
I've use latest marlin fw (2.0.7.2) and i work now. So I think you have an issue on your build.

**Comment by mks-viva** [comment]
Thank you for your feedback, but we have tested the firmware and it works normally.
